---
# Handlers pour le rôle wazuh-manager
- name: restart wazuh-manager
  ansible.builtin.systemd:
    name: wazuh-manager
    state: restarted
    daemon_reload: yes
  listen: "restart wazuh-manager"
