# Fichier d'inventaire pour l'environnement de production
# Les noms d'hôtes et adresses IP de production seront listés ici.
# Exemple :
# [wazuh_manager]
# wazuh-mgr-prod.ecole.lan ansible_host=10.1.1.10
#
# [wazuh_indexer]
# wazuh-idx-prod.ecole.lan ansible_host=10.1.1.11
